In [39]:
import glob
import os.path
import numpy as np
import cv2
import scipy.io
import matplotlib.pyplot as plt

headplate = []
reference = []
minimum = []
maximum = []
median = []
filenames = []

for fn_mat in sorted(glob.glob('./Aki/LeftPawManual*.mat')):
    fn_bin = fn_mat[:-4]+'.bin'
    fn_npy = fn_mat[:-4]+'.npy'
    fn = fn_mat[20:-4]
    fn_avi = './Aki/'+fn+'.avi'
    print(fn)
    filenames.append(fn)

    mat = scipy.io.loadmat(fn_mat)

    maximum.append(np.percentile(mat['Left_Paw'][mat['Left_Paw'][:,0]>0,:],99,axis=0))
    minimum.append(np.percentile(mat['Left_Paw'][mat['Left_Paw'][:,0]>0,:],1,axis=0))
    median.append(np.median(mat['Left_Paw'][mat['Left_Paw'][:,0]>0,:],axis=0))
    try:
        headplate_x = np.round(mat['HeadPlatePosition']).astype(np.int)[0][0]
        headplate_y = np.round(mat['HeadPlatePosition']).astype(np.int)[0][1]
        # [y, x] in np.array
    except:
        headplate_x = np.nan
        headplate_y = np.nan
        print("  HeadPlatePosition Not Found")
    try:
        reference_x = np.round(mat['Reference_pt']).astype(np.int)[0][0]
        reference_y = np.round(mat['Reference_pt']).astype(np.int)[0][1]
        # [y, x] in np.array
    except:
        reference_x = 200
        reference_y = 16
        print("  Reference_pt Not Found")
    headplate.append((headplate_x, headplate_y))
    reference.append((reference_x, reference_y))
    
headplate = np.array(headplate)
reference = np.array(reference)
maximum = np.array(maximum)
minimum = np.array(minimum)
median = np.array(median)




HL186_170718_L23_F1
  HeadPlatePosition Not Found
HL237_180117_L23_F2
HL237_180118_L23_F1
  HeadPlatePosition Not Found
HL241_180117_training
HL241_180130_opto_wholetrial
HL242_180117_training
HL246_180314_ladder
  HeadPlatePosition Not Found
HL246_180326_L23_F1_Ladder
HL246_180326_L23_F1_Wheel
MD001_170713
MD001_170723
MD001_170724_rec1
MD002_170713_rec2
MD002_170724_rec1
  HeadPlatePosition Not Found
MD003_170721
MD003_170731
MD003_170801_rec1
MD004_170721
MD004_170802
MD009_170808
MD010_170808


In [28]:
print(median-headplate)
print(median-reference)

[[         nan          nan]
 [198.91164241 -17.68503119]
 [         nan          nan]
 [ 62.99480249  69.16112266]
 [ 77.8950104   72.16112266]
 [ 66.97401247  69.16943867]
 [         nan          nan]
 [207.09459459  70.0987526 ]
 [197.14033264  48.11122661]
 [101.15784314  93.47941176]
 [ 74.27352941  96.60098039]
 [ 62.30686275  96.72254902]
 [ 84.3127451   93.47941176]
 [         nan          nan]
 [ 72.52910603  91.06964657]
 [ 56.67047817  92.07796258]
 [ 43.67879418  90.07796258]
 [ 74.52079002  98.06133056]
 [ 38.73700624  89.09459459]
 [139.58731809  77.12370062]
 [ 97.76611227  72.14449064]]
[[33.59028865 66.18853961]
 [42.91164241 36.31496881]
 [ 4.88901602 39.48855835]
 [43.99480249 45.16112266]
 [45.8950104  45.16112266]
 [35.97401247 43.16943867]
 [50.79321663 91.09737418]
 [47.09459459 65.0987526 ]
 [33.14033264 65.11122661]
 [68.15784314 64.47941176]
 [75.27352941 69.60098039]
 [63.30686275 66.72254902]
 [62.3127451  67.47941176]
 [30.64553015 63.08627859]
 [65.5291060

In [40]:
print(minimum-headplate)
print(minimum-reference)

[[         nan          nan]
 [131.19438669 -36.60602911]
 [         nan          nan]
 [-44.55613306  10.40644491]
 [ 18.14449064  43.28170478]
 [-33.60602911   6.43139293]
 [         nan          nan]
 [137.38565489  45.2027027 ]
 [118.46881497  21.22349272]
 [ 18.50686275  60.60686275]
 [  1.95392157  63.73782353]
 [  5.95392157  68.54607843]
 [-23.69705882  61.54607843]
 [         nan          nan]
 [ -1.16320166  65.17775468]
 [ -3.64767152  67.18191268]
 [-25.03430353  63.35952183]
 [ 10.78690229  74.16112266]
 [-20.01767152  67.18607069]
 [ 73.86174636  56.21101871]
 [ 54.94490644  55.21517672]]
[[-13.13721833  38.29780252]
 [-24.80561331  17.39397089]
 [-76.83693364  14.27803204]
 [-63.55613306 -13.59355509]
 [-13.85550936  16.28170478]
 [-64.60602911 -19.56860707]
 [-25.2615122   64.01829268]
 [-22.61434511  40.2027027 ]
 [-45.53118503  38.22349272]
 [-14.49313725  31.60686275]
 [  2.95392157  36.73782353]
 [  6.95392157  38.54607843]
 [-45.69705882  35.54607843]
 [  1.1984823

In [41]:
print(maximum-headplate)
print(maximum-reference)

[[         nan          nan]
 [289.53326403  -5.73492723]
 [         nan          nan]
 [138.67879418  94.05717256]
 [167.91912682  84.11122661]
 [148.63305613  87.13442827]
 [         nan          nan]
 [319.62474012  87.02806653]
 [336.55821206  66.03638254]
 [163.14607843 122.59509804]
 [151.28921569 106.93235294]
 [138.38333333 117.38529412]
 [151.15672549 106.62843137]
 [         nan          nan]
 [146.22141372 108.247921  ]
 [155.25883576 105.02390852]
 [141.27130977 105.01559252]
 [135.26715177 111.00727651]
 [110.49738046 105.02806653]
 [229.21309771  94.05301455]
 [199.34199584  85.09043659]]
[[144.76310671  82.73063196]
 [133.53326403  48.26507277]
 [104.63501144  54.83409611]
 [119.67879418  70.05717256]
 [135.91912682  57.11122661]
 [117.63305613  61.13442827]
 [168.30121951 103.33964989]
 [159.62474012  82.02806653]
 [172.55821206  83.03638254]
 [130.14607843  93.59509804]
 [152.28921569  79.93235294]
 [139.38333333  87.38529412]
 [129.15672549  80.62843137]
 [117.2837837

In [27]:
print(headplate-reference)

[[  nan   nan]
 [-156.   54.]
 [  nan   nan]
 [ -19.  -24.]
 [ -32.  -27.]
 [ -31.  -26.]
 [  nan   nan]
 [-160.   -5.]
 [-164.   17.]
 [ -33.  -29.]
 [   1.  -27.]
 [   1.  -30.]
 [ -22.  -26.]
 [  nan   nan]
 [  -7.  -27.]
 [ -18.  -29.]
 [  17.  -24.]
 [ -22.  -34.]
 [ -16.  -29.]
 [ -96.  -28.]
 [ -92.  -28.]]


In [52]:
print(np.nanmax(maximum-headplate,axis=0))
print(np.nanmax(maximum-reference,axis=0))

[336.55821206 122.59509804]
[172.55821206 103.33964989]


In [51]:
print(np.nanmin(minimum-headplate,axis=0))
print(np.nanmin(minimum-reference,axis=0))

[-44.55613306 -36.60602911]
[-76.83693364 -19.56860707]


In [44]:
np.nanmedian(headplate-reference,axis=0)

array([-22., -27.])

In [ ]:
headplate-reference = [-15, -30]

In [48]:
np.max(maximum,axis=0)

array([433.28921569, 138.59509804])

In [49]:
np.min(minimum,axis=0)

array([128.46881497,  17.43139293])

In [46]:
np.min(reference,axis=0)

array([171,   7])

In [47]:
np.max(reference,axis=0)

array([303,  45])

In [50]:
reference

array([[223,  40],
       [219,   9],
       [246,   7],
       [198,  37],
       [220,  37],
       [211,  37],
       [229,  10],
       [171,  32],
       [174,  29],
       [259,  45],
       [281,  38],
       [277,  39],
       [247,  42],
       [295,  37],
       [288,  40],
       [281,  39],
       [257,  36],
       [303,  42],
       [281,  38],
       [296,  42],
       [291,  42]])

In [53]:
headplate

array([[ nan,  nan],
       [ 63.,  63.],
       [ nan,  nan],
       [179.,  13.],
       [188.,  10.],
       [180.,  11.],
       [ nan,  nan],
       [ 11.,  27.],
       [ 10.,  46.],
       [226.,  16.],
       [282.,  11.],
       [278.,   9.],
       [225.,  16.],
       [ nan,  nan],
       [281.,  13.],
       [263.,  10.],
       [274.,  12.],
       [281.,   8.],
       [265.,   9.],
       [200.,  14.],
       [199.,  14.]])